### ISSUE TITLE
Question about the object class

### ISSUE THREAD

**Issue by dream-toy** [unmannedlab/LiDARNet#1]
Hi, Peng Jiang.

Firstly, thank you for your brilliant work!

But I have a question. In Tab. I, there is an **object** class. I can't find **object** class in your paper, so I want to know which classes are turned into object class in your paper.

Please help......

**Comment by maskjp** [comment]
Hi @dream-toy,

Thank you for your interest in LiDARNet. The table is from our paper. Are you referring to our [latest version](https://arxiv.org/pdf/2003.01174.pdf)?

I uploaded the [label files](https://github.com/unmannedlab/LiDARNet/tree/main/datasets) in this git. You can find the definition of classes and how we merged classes. Please take a look at them.

I am planning to release the code recently. But my coding is a mess, so I want to add some comments to make it readable.

Anyway, I hope the label files can help you.

Best wishes!

**Comment by yuan-zm** [comment]
> Hi @dream-toy,
> 
> Thank you for your interest in LiDARNet. The table is from our paper. Are you referring to our [latest version](https://arxiv.org/pdf/2003.01174.pdf)?
> 
> I uploaded the [label files](https://github.com/unmannedlab/LiDARNet/tree/main/datasets) in this git. You can find the definition of classes and how we merged classes. Please take a look at them.
> 
> I am planning to release the code recently. But my coding is a mess, so I want to add some comments to make it readable.
> 
> Anyway, I hope the label files can help you.
> 
> Best wishes!

Thank you for your quick reply. It helps me a lot. And I am looking forward to your code.

**Comment by yuan-zm** [comment]
Hi, Peng Jiang,

As shown in semanticusl.yaml, you are using [ 0, 1, 2, 3, 4, 5, 6, 7,  9 , 10] to train. But in your paper "Our dataset has 16578 unlabeled scans for domain adaptation training and 1200 labeled scans for evaluation. ". I did not find a detailed description of the data division. This confuses me for a long time.  

Could you please give us a detailed description of the data division in your paper? It will be much easier for us to compare with your method.

**Comment by maskjp** [comment]
Hi, @dream-toy,

Have you downloaded the SemanticUSL? We didn't use the split part in the YAML file. Sorry, I forget to delete that part in the file.

We define the split in other places. The SemanticUSL has around 70 sequences. The sequence 3,12,21,32 are labeled, and the others are unlabeled or partly labeled. I think there's a readme file that describes this information in the SemanticUSL zip file. If there's not, please tell me. 

When train for domain adaptation from the SemanticKITTI to the SemanticUSL, we used all unlabeled sequences to train the model and use the label to evaluate. 

I hope this solves your problem.

Best wishes!

**Comment by yuan-zm** [comment]
Thank you for your generous help. This is what I want to know.

Yes, there is a README file in the SemanticUSL.zip. 

Sorry, I still have a question. How about the semanticPOSS?  https://github.com/unmannedlab/LiDARNet/blob/b4bcb870959a576a0724824097fb6a69bffbb184/datasets/semantickposs/semanticposs.yaml#L122
In this YAML file, you are using six sequences to train the model. And semanticPOSS only has six sequences. Are you using all these six sequences to train the model, and then using these six sequences to evaluate?

**Comment by maskjp** [comment]
Hi, @dream-toy,

For SemanticPOSS, I used the sequence [0,1,2,3,4] for training and [5] for evaluation. 
And for SemanticKITTI, I used [ 0,1,2,3,4,5,6,7,9,10] for training and [8] for evaluation. 

Best wishes!

**Comment by yuan-zm** [comment]
Many thanks for your reply. It does help me a lot!
